### ISSUE TITLE
[BUG] Image corruption of original camera source when using v4l2loopback device with some VC software (zoom)

### ISSUE THREAD

**Issue by aenertia** [umlaeute/v4l2loopback#407] opened 2021-02-26 23:44 UTC
#### Title
As of commit f62fb9076b6313e5eb82fdcaceadb6b3052f346e ; v4l2loopback works but when a real camera device is selected and used i.e via OBS the original source becomes corrupt and looks garbage; corrupted pixel format, colour pallets - grey with fluro bands etc.

Was working ok previously when the v4l2 device was used within Zoom. Interesting fully generated scenes not including a real v4l2source remain intact. 

This behaviour is reported in several places on the OBS forums i.e 
https://obsproject.com/forum/threads/obs-virtual-cam-output-is-blury-and-pixelish.118650/
Which also appear to be v4l2 related. There are some other Windows platform bug reports which also seem similar.

### Step 2: Describe your environment

  * `v4l2loopback` version:
```
[ 2119.910771] v4l2loopback: loading out-of-tree module taints kernel.
[ 2119.910821] v4l2loopback: module verification failed: signature and/or required key missing - tainting kernel
[ 2119.913842] v4l2loopback driver version 0.12.5 loaded
```

  * kernel version: _____
`Linux fedora 5.12.0-0.rc0.20210224gitc03c21ba6f4e.160.fc35.x86_64 #1 SMP Wed Feb 24 17:57:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

          uname -a

  * Distribution (+version): _____

```
[aenertia@fedora v4l2loopback]$ cat /etc/redhat-release 
Fedora release 35 (Rawhide)
```

  
#### Steps to reproduce:

  1. Load v4l2 source (i.e camlink4) into a scene in obs
  2. Create another scene i.e clock etc
  3. run start virtual cam; observe loading of v4l2module
  4. load zoom client (using flathub version); select v4l2source
  5. switch scene to v4l2 source, observe hinkyness

**Comment by umlaeute** [comment] 2021-03-18 12:59
first of all: please note that `v4l2` is the entire `video4linux2`-subsystem. *this* driver here is just one of zillions of drivers that use this subsystem (it's one of the very few that provide a loopback device).
please don't mix the two terms.

from what i gather from your description and the forum posts, this is about image degradation (slightly lowering the quality of the input image) rather than image *corruption*, which - at least for me - represents glitch artifacts in the images.

now, people in the forum state, that the image degradation happens on Win10 and Linux, NDI and VirtualCam.
`v4l2loopback` is *only* used in the Linux/VirtualCam combination, so it cannot be the culprit for Win10/NDI, Win10/VirtualCam and Linux/NDI.
which makes me think that the issue is *not at all* an issue of `v4l2loopback`, but either of *OBS* or *zoom*.

furthermore: `v4l2loopback` does not do anything with the images themselves: it just queues the data and hands them out *without any modification*.

finally, i have no idea what yo umean by *hinkyness*.

therefore i'm closing this, as "not solvable on the v4l2loopback side".

**Closed by umlaeute** 2021-03-18 12:59 UTC
Labels: needs triage
