### ISSUE TITLE
Loading module with exclusive_caps=1 generates no output and kernel warnings 

### ISSUE THREAD

**Issue by divinitus** [umlaeute/v4l2loopback#279] opened 2020-04-09 18:37 UTC
* `v4l2loopback` version:         

          v4l2loopback driver version 0.12.3 loaded

  * kernel version: 

          Linux legion.osec.pl 5.5.15-200.fc31.x86_64 #1 SMP Thu Apr 2 19:16:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

  * Distribution (+version): _____

          LSB Version:	:core-4.1-amd64:core-4.1-noarch
          Distributor ID:	Fedora
          Description:	Fedora release 31 (Thirty One)
          Release:	31
          Codename:	ThirtyOne

  
### Describe the problem:
Loading the module with:
          modprobe v4l2loopback devices=1 card_label="FakeCam"

Then running OSB Studio with v4l2sink work great on https://webcamtests.com/
However the cam is not being recognized on Bluejeans or Google Hangouts.

Loading the module with

          modprobe v4l2loopback devices=1 card_label="FakeCam" exclusive_caps=1

The Cam is visible on Bluejeans and hamgouts but no output is visible.
It also makes kernel generate lots of messages like that:

[  709.423141] ------------[ cut here ]------------
[  709.423147] WARNING: CPU: 3 PID: 4880 at drivers/media/v4l2-core/v4l2-ioctl.c:1079 v4l_querycap+0x86/0xa0 [videodev]
[  709.423148] Hardware name: LENOVO 81HD/LNVNB161216, BIOS 8XCN34WW(V2.03) 11/19/2019
[  709.423148] Modules linked in: v4l2loopback(OE)
[  709.423153] RIP: 0010:v4l_querycap+0x86/0xa0 [videodev]
[  709.423154]  thunderbolt ccm
[  709.423156] Code: ca 00 00 00 80 48 b9 00 00 20 00 00 00 20 00 48 0b 4b 54 21 d6 39 f2 75 11 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 0f 0b eb d2 <0f> 0b 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 66 66 2e 0f 1f 84 00
[  709.423156]  rfcomm xt_CHECKSUM
[  709.423158] RSP: 0018:ffffb81109177cb8 EFLAGS: 00010202
[  709.423158]  xt_MASQUERADE nf_nat_tftp nf_conntrack_tftp
[  709.423160]  tun bridge
[  709.423161] RAX: 0000000000000000 RBX: ffffb81109177db8 RCX: 8520800285208002
[  709.423162]  stp llc
[  709.423163] RDX: 0000000085008003 RSI: 0000000085008002 RDI: 0000000000000000
[  709.423164]  nf_conntrack_netbios_ns nf_conntrack_broadcast
[  709.423165] RBP: ffff9bd21e35f000 R08: ffffb81109177e01 R09: 0000000000ffff0a
[  709.423165]  xt_CT ip6t_REJECT
[  709.423167] R10: 0000000000000000 R11: 0000000000000056 R12: ffff9bd26de65a00
[  709.423167]  nf_reject_ipv6 ip6t_rpfilter
[  709.423169] R13: ffff9bd3641c3e20 R14: ffffffffc1f5b380 R15: 0000000000000000
[  709.423169]  ipt_REJECT nf_reject_ipv4
[  709.423171] FS:  00007f0866ffd700(0000) GS:ffff9bd392700000(0000) knlGS:0000000000000000
[  709.423171]  xt_conntrack ebtable_nat
[  709.423172] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  709.423173]  ebtable_broute ip6table_nat
[  709.423174] CR2: 00007f2e5aa56390 CR3: 0000000815758003 CR4: 00000000003606e0
[  709.423175]  ip6table_mangle ip6table_raw
[  709.423176] Call Trace:
[  709.423176]  ip6table_security iptable_nat nf_nat iptable_mangle iptable_raw
[  709.423182]  __video_do_ioctl+0x174/0x3c0 [videodev]
[  709.423182]  iptable_security nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip_set nfnetlink
[  709.423188]  video_usercopy+0x289/0x600 [videodev]
[  709.423189]  ebtable_filter ebtables ip6table_filter
[  709.423194]  ? v4l_enum_fmt+0x1820/0x1820 [videodev]
[  709.423194]  ip6_tables iptable_filter cmac bnep dm_crypt vfat fat
[  709.423200]  v4l2_ioctl+0x48/0x50 [videodev]
[  709.423200]  snd_sof_pci snd_sof_intel_byt
[  709.423202]  do_vfs_ioctl+0x461/0x6d0
[  709.423203]  snd_sof_intel_ipc snd_sof_xtensa_dsp snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_sof
[  709.423205]  ksys_ioctl+0x5e/0x90
[  709.423206]  x86_pkg_temp_thermal intel_powerclamp nvidia_drm(POE)
[  709.423208]  __x64_sys_ioctl+0x16/0x20
[  709.423209]  nvidia_modeset(POE) snd_soc_skl coretemp
[  709.423212]  do_syscall_64+0x5b/0x1c0
[  709.423212]  nvidia_uvm(OE) kvm_intel snd_soc_sst_ipc
[  709.423215]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  709.423216]  snd_soc_sst_dsp snd_hda_ext_core
[  709.423217] RIP: 0033:0x7f08d590d35b
[  709.423218]  snd_soc_acpi_intel_match snd_soc_acpi
[  709.423219] Code: 0f 1e fa 48 8b 05 2d 9b 0c 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d fd 9a 0c 00 f7 d8 64 89 01 48
[  709.423220]  kvm snd_soc_core
[  709.423221] RSP: 002b:00007f0866ffc3a8 EFLAGS: 00000246
[  709.423222]  snd_hda_codec_hdmi iTCO_wdt
[  709.423223]  ORIG_RAX: 0000000000000010
[  709.423223]  mei_hdcp iTCO_vendor_support
[  709.423225] RAX: ffffffffffffffda RBX: 00007f08b8262aa0 RCX: 00007f08d590d35b
[  709.423225]  intel_rapl_msr iwlmvm
[  709.423226] RDX: 00007f0866ffc428 RSI: ffffffff80685600 RDI: 0000000000000067
[  709.423227]  irqbypass uvcvideo
[  709.423228] RBP: 00007f0866ffc4c0 R08: 0000000000000000 R09: 0000000000000000
[  709.423229]  snd_hda_codec_realtek snd_compress
[  709.423230] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000067
[  709.423230]  ac97_bus videobuf2_vmalloc
[  709.423232] R13: 00007f0866ffc428 R14: 00007f08b8262aa1 R15: 0000559c3a96f070
[  709.423232]  crct10dif_pclmul videobuf2_memops crc32_pclmul snd_pcm_dmaengine snd_hda_codec_generic videobuf2_v4l2
[  709.423234] ---[ end trace 67bc71b3671b2549 ]---
[  709.423234]  mac80211 ghash_clmulni_intel videobuf2_common ledtrig_audio intel_cstate snd_hda_intel snd_intel_dspcfg intel_uncore snd_hda_codec videodev pcspkr libarc4 snd_hda_core intel_rapl_perf btusb mei_me intel_wmi_thunderbolt wmi_bmof iwlwifi i2c_i801 snd_hwdep mei nvidia(POE) mc snd_seq btrtl btbcm snd_seq_device btintel bluetooth snd_pcm joydev snd_timer cfg80211 ipmi_devintf snd ecdh_generic ecc ipmi_msghandler idma64 intel_pch_thermal soundcore processor_thermal_device ucsi_acpi intel_rapl_common typec_ucsi intel_soc_dts_iosf typec ideapad_laptop sparse_keymap rfkill int3400_thermal int3403_thermal int340x_thermal_zone acpi_thermal_rel acpi_pad auth_rpcgss sunrpc ip_tables i915 hid_multitouch crc32c_intel i2c_algo_bit serio_raw drm_kms_helper drm r8169 i2c_hid wmi video pinctrl_cannonlake pinctrl_intel i2c_dev fuse [last unloaded: v4l2loopback]
[  709.423251] CPU: 3 PID: 4880 Comm: pipewire Tainted: P        W  OE     5.5.15-200.fc31.x86_64 #1
[  709.423252] Hardware name: LENOVO 81HD/LNVNB161216, BIOS 8XCN34WW(V2.03) 11/19/2019
[  709.423256] RIP: 0010:v4l_querycap+0x86/0xa0 [videodev]
[  709.423257] Code: ca 00 00 00 80 48 b9 00 00 20 00 00 00 20 00 48 0b 4b 54 21 d6 39 f2 75 11 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 0f 0b eb d2 <0f> 0b 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 66 66 2e 0f 1f 84 00
[  709.423258] RSP: 0018:ffffb81109697cb8 EFLAGS: 00010202
[  709.423259] RAX: 0000000000000000 RBX: ffffb81109697db8 RCX: 8520800285208002
[  709.423260] RDX: 0000000085008003 RSI: 0000000085008002 RDI: 0000000000000000
[  709.423261] RBP: ffff9bd21e35f000 R08: ffffb81109697e01 R09: 0000000000ffff0a
[  709.423261] R10: 0000000000000000 R11: 0000000000000056 R12: ffff9bd23463f300
[  709.423262] R13: ffff9bd21ef95320 R14: ffffffffc1f5b380 R15: 0000000000000000
[  709.423263] FS:  00007fdeca7d0b80(0000) GS:ffff9bd3926c0000(0000) knlGS:0000000000000000
[  709.423264] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  709.423265] CR2: 000056257ac12e50 CR3: 000000073463a003 CR4: 00000000003606e0
[  709.423265] Call Trace:
[  709.423270]  __video_do_ioctl+0x174/0x3c0 [videodev]
[  709.423276]  video_usercopy+0x289/0x600 [videodev]
[  709.423281]  ? v4l_enum_fmt+0x1820/0x1820 [videodev]
[  709.423286]  v4l2_ioctl+0x48/0x50 [videodev]
[  709.423288]  do_vfs_ioctl+0x461/0x6d0
[  709.423290]  ksys_ioctl+0x5e/0x90
[  709.423292]  __x64_sys_ioctl+0x16/0x20
[  709.423296]  do_syscall_64+0x5b/0x1c0
[  709.423298]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  709.423299] RIP: 0033:0x7fdeca8d135b
[  709.423301] Code: 0f 1e fa 48 8b 05 2d 9b 0c 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d fd 9a 0c 00 f7 d8 64 89 01 48
[  709.423301] RSP: 002b:00007ffdf9d940c8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[  709.423302] RAX: ffffffffffffffda RBX: ffffffff80685600 RCX: 00007fdeca8d135b
[  709.423303] RDX: 0000558ca8b150d4 RSI: ffffffff80685600 RDI: 0000000000000019
[  709.423304] RBP: 0000558ca8b150d4 R08: 0000000000000000 R09: 0000000000000000
[  709.423304] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000000
[  709.423305] R13: 0000000000000019 R14: 0000000000000000 R15: 00007ffdf9d94ed0
[  709.423307] ---[ end trace 67bc71b3671b254a ]---
[  710.407855] ------------[ cut here ]------------
[  710.407878] WARNING: CPU: 1 PID: 3502 at drivers/media/v4l2-core/v4l2-ioctl.c:1074 v4l_querycap+0x82/0xa0 [videodev]
[  710.407880] Modules linked in: v4l2loopback(OE) thunderbolt ccm rfcomm xt_CHECKSUM xt_MASQUERADE nf_nat_tftp nf_conntrack_tftp tun bridge stp llc nf_conntrack_netbios_ns nf_conntrack_broadcast xt_CT ip6t_REJECT nf_reject_ipv6 ip6t_rpfilter ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ebtable_broute ip6table_nat ip6table_mangle ip6table_raw ip6table_security iptable_nat nf_nat iptable_mangle iptable_raw iptable_security nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip_set nfnetlink ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter cmac bnep dm_crypt vfat fat snd_sof_pci snd_sof_intel_byt snd_sof_intel_ipc snd_sof_xtensa_dsp snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_sof x86_pkg_temp_thermal intel_powerclamp nvidia_drm(POE) nvidia_modeset(POE) snd_soc_skl coretemp nvidia_uvm(OE) kvm_intel snd_soc_sst_ipc snd_soc_sst_dsp snd_hda_ext_core snd_soc_acpi_intel_match snd_soc_acpi kvm snd_soc_core snd_hda_codec_hdmi iTCO_wdt mei_hdcp
[  710.407924]  iTCO_vendor_support intel_rapl_msr iwlmvm irqbypass uvcvideo snd_hda_codec_realtek snd_compress ac97_bus videobuf2_vmalloc crct10dif_pclmul videobuf2_memops crc32_pclmul snd_pcm_dmaengine snd_hda_codec_generic videobuf2_v4l2 mac80211 ghash_clmulni_intel videobuf2_common ledtrig_audio intel_cstate snd_hda_intel snd_intel_dspcfg intel_uncore snd_hda_codec videodev pcspkr libarc4 snd_hda_core intel_rapl_perf btusb mei_me intel_wmi_thunderbolt wmi_bmof iwlwifi i2c_i801 snd_hwdep mei nvidia(POE) mc snd_seq btrtl btbcm snd_seq_device btintel bluetooth snd_pcm joydev snd_timer cfg80211 ipmi_devintf snd ecdh_generic ecc ipmi_msghandler idma64 intel_pch_thermal soundcore processor_thermal_device ucsi_acpi intel_rapl_common typec_ucsi intel_soc_dts_iosf typec ideapad_laptop sparse_keymap rfkill int3400_thermal int3403_thermal int340x_thermal_zone acpi_thermal_rel acpi_pad auth_rpcgss sunrpc ip_tables i915 hid_multitouch crc32c_intel i2c_algo_bit serio_raw drm_kms_helper drm r8169
[  710.407973]  i2c_hid wmi video pinctrl_cannonlake pinctrl_intel i2c_dev fuse [last unloaded: v4l2loopback]
[  710.407984] CPU: 1 PID: 3502 Comm: teams Tainted: P        W  OE     5.5.15-200.fc31.x86_64 #1
[  710.407986] Hardware name: LENOVO 81HD/LNVNB161216, BIOS 8XCN34WW(V2.03) 11/19/2019
[  710.407999] RIP: 0010:v4l_querycap+0x82/0xa0 [videodev]
[  710.408002] Code: 8b 73 54 81 ca 00 00 00 80 48 b9 00 00 20 00 00 00 20 00 48 0b 4b 54 21 d6 39 f2 75 11 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 <0f> 0b eb d2 0f 0b 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 66 66 2e
[  710.408005] RSP: 0018:ffffb81108e4fcb8 EFLAGS: 00010297
[  710.408008] RAX: 0000000000000000 RBX: ffffb81108e4fdb8 RCX: 0000000000000001
[  710.408010] RDX: 0000000085008003 RSI: 0000000000000000 RDI: 0000000000000000
[  710.408012] RBP: ffff9bd21e35f000 R08: ffffb81108e4fe01 R09: 0000000000ffff0a
[  710.408014] R10: 0000000000000000 R11: 0000000000000056 R12: ffff9bd30f806400
[  710.408015] R13: ffff9bd225d5fba0 R14: ffffffffc1f5b380 R15: 0000000000000000
[  710.408018] FS:  00007f60dd7fa700(0000) GS:ffff9bd392640000(0000) knlGS:0000000000000000
[  710.408020] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  710.408022] CR2: 00005606ab9bbb34 CR3: 00000007d9ed0004 CR4: 00000000003606e0
[  710.408024] Call Trace:
[  710.408043]  __video_do_ioctl+0x174/0x3c0 [videodev]
[  710.408053]  ? update_load_avg+0x78/0x5f0
[  710.408066]  video_usercopy+0x289/0x600 [videodev]
[  710.408078]  ? v4l_enum_fmt+0x1820/0x1820 [videodev]
[  710.408091]  v4l2_ioctl+0x48/0x50 [videodev]
[  710.408096]  do_vfs_ioctl+0x461/0x6d0
[  710.408102]  ksys_ioctl+0x5e/0x90
[  710.408106]  __x64_sys_ioctl+0x16/0x20
[  710.408112]  do_syscall_64+0x5b/0x1c0
[  710.408120]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  710.408123] RIP: 0033:0x7f615bc6435b
[  710.408127] Code: 0f 1e fa 48 8b 05 2d 9b 0c 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d fd 9a 0c 00 f7 d8 64 89 01 48
[  710.408129] RSP: 002b:00007f60dd7efee8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[  710.408132] RAX: ffffffffffffffda RBX: 0000000000000047 RCX: 00007f615bc6435b
[  710.408134] RDX: 00007f60dd7f0120 RSI: ffffffff80685600 RDI: 0000000000000047
[  710.408136] RBP: ffffffff80685600 R08: 0000000000000000 R09: 00007f60dd7f0060
[  710.408138] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000047
[  710.408139] R13: 00007f60dd7f0120 R14: 0000000000000015 R15: 00007f611366b039
[  710.408144] ---[ end trace 67bc71b3671b254b ]---
[  710.408191] ------------[ cut here ]------------
[  710.408204] WARNING: CPU: 1 PID: 3502 at drivers/media/v4l2-core/v4l2-ioctl.c:1079 v4l_querycap+0x86/0xa0 [videodev]
[  710.408204] Modules linked in: v4l2loopback(OE) thunderbolt ccm rfcomm xt_CHECKSUM xt_MASQUERADE nf_nat_tftp nf_conntrack_tftp tun bridge stp llc nf_conntrack_netbios_ns nf_conntrack_broadcast xt_CT ip6t_REJECT nf_reject_ipv6 ip6t_rpfilter ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ebtable_broute ip6table_nat ip6table_mangle ip6table_raw ip6table_security iptable_nat nf_nat iptable_mangle iptable_raw iptable_security nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c ip_set nfnetlink ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter cmac bnep dm_crypt vfat fat snd_sof_pci snd_sof_intel_byt snd_sof_intel_ipc snd_sof_xtensa_dsp snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_sof x86_pkg_temp_thermal intel_powerclamp nvidia_drm(POE) nvidia_modeset(POE) snd_soc_skl coretemp nvidia_uvm(OE) kvm_intel snd_soc_sst_ipc snd_soc_sst_dsp snd_hda_ext_core snd_soc_acpi_intel_match snd_soc_acpi kvm snd_soc_core snd_hda_codec_hdmi iTCO_wdt mei_hdcp
[  710.408241]  iTCO_vendor_support intel_rapl_msr iwlmvm irqbypass uvcvideo snd_hda_codec_realtek snd_compress ac97_bus videobuf2_vmalloc crct10dif_pclmul videobuf2_memops crc32_pclmul snd_pcm_dmaengine snd_hda_codec_generic videobuf2_v4l2 mac80211 ghash_clmulni_intel videobuf2_common ledtrig_audio intel_cstate snd_hda_intel snd_intel_dspcfg intel_uncore snd_hda_codec videodev pcspkr libarc4 snd_hda_core intel_rapl_perf btusb mei_me intel_wmi_thunderbolt wmi_bmof iwlwifi i2c_i801 snd_hwdep mei nvidia(POE) mc snd_seq btrtl btbcm snd_seq_device btintel bluetooth snd_pcm joydev snd_timer cfg80211 ipmi_devintf snd ecdh_generic ecc ipmi_msghandler idma64 intel_pch_thermal soundcore processor_thermal_device ucsi_acpi intel_rapl_common typec_ucsi intel_soc_dts_iosf typec ideapad_laptop sparse_keymap rfkill int3400_thermal int3403_thermal int340x_thermal_zone acpi_thermal_rel acpi_pad auth_rpcgss sunrpc ip_tables i915 hid_multitouch crc32c_intel i2c_algo_bit serio_raw drm_kms_helper drm r8169
[  710.408278]  i2c_hid wmi video pinctrl_cannonlake pinctrl_intel i2c_dev fuse [last unloaded: v4l2loopback]
[  710.408286] CPU: 1 PID: 3502 Comm: teams Tainted: P        W  OE     5.5.15-200.fc31.x86_64 #1
[  710.408288] Hardware name: LENOVO 81HD/LNVNB161216, BIOS 8XCN34WW(V2.03) 11/19/2019
[  710.408299] RIP: 0010:v4l_querycap+0x86/0xa0 [videodev]
[  710.408302] Code: ca 00 00 00 80 48 b9 00 00 20 00 00 00 20 00 48 0b 4b 54 21 d6 39 f2 75 11 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 0f 0b eb d2 <0f> 0b 48 89 4b 54 5b 5d 41 5c 41 5d 41 5e c3 66 66 2e 0f 1f 84 00
[  710.408303] RSP: 0018:ffffb81108e4fcb8 EFLAGS: 00010202
[  710.408306] RAX: 0000000000000000 RBX: ffffb81108e4fdb8 RCX: 8520800285208002
[  710.408307] RDX: 0000000085008003 RSI: 0000000085008002 RDI: 0000000000000000
[  710.408309] RBP: ffff9bd21e35f000 R08: ffffb81108e4fe01 R09: 0000000000ffff0a
[  710.408311] R10: 0000000000000000 R11: 0000000000000056 R12: ffff9bd30f806400
[  710.408313] R13: ffff9bd225d5fba0 R14: ffffffffc1f5b380 R15: 0000000000000000
[  710.408315] FS:  00007f60dd7fa700(0000) GS:ffff9bd392640000(0000) knlGS:0000000000000000
[  710.408317] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  710.408319] CR2: 00005606ab9bbb34 CR3: 00000007d9ed0004 CR4: 00000000003606e0
[  710.408320] Call Trace:
[  710.408333]  __video_do_ioctl+0x174/0x3c0 [videodev]
[  710.408339]  ? update_load_avg+0x78/0x5f0
[  710.408351]  video_usercopy+0x289/0x600 [videodev]
[  710.408362]  ? v4l_enum_fmt+0x1820/0x1820 [videodev]
[  710.408375]  v4l2_ioctl+0x48/0x50 [videodev]
[  710.408379]  do_vfs_ioctl+0x461/0x6d0
[  710.408384]  ksys_ioctl+0x5e/0x90
[  710.408388]  __x64_sys_ioctl+0x16/0x20
[  710.408393]  do_syscall_64+0x5b/0x1c0
[  710.408399]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  710.408401] RIP: 0033:0x7f615bc6435b
[  710.408404] Code: 0f 1e fa 48 8b 05 2d 9b 0c 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d fd 9a 0c 00 f7 d8 64 89 01 48
[  710.408406] RSP: 002b:00007f60dd7efee8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[  710.408408] RAX: ffffffffffffffda RBX: 0000000000000047 RCX: 00007f615bc6435b
[  710.408410] RDX: 00007f60dd7f0120 RSI: ffffffff80685600 RDI: 0000000000000047
[  710.408411] RBP: ffffffff80685600 R08: 0000000000000000 R09: 00007f60dd7f0060
[  710.408413] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000047
[  710.408415] R13: 00007f60dd7f0120 R14: 0000000000000015 R15: 00007f611366b039
[  710.408419] ---[ end trace 67bc71b3671b254c ]---

**Comment by derneue** [comment] 2020-04-09 18:44
I think this is a duplicate of #257

**Closed** 2020-04-09 21:15 UTC
