### ISSUE TITLE
Ubuntu 20.10 install issue

### ISSUE THREAD

**Issue by dylanpjx** [umlaeute/v4l2loopback#366] opened 2020-10-28 01:55 UTC
On Ubuntu 20.10, kernel `5.8.0-7625-generic`

`sudo apt install v4l2loopback-dkms` returns error:
```
ERROR (dkms apport): kernel package linux-headers-5.8.0-7625-generic is not supported
Error! Bad return status for module build on kernel: 5.8.0-7625-generic (x86_64)
```

Manually building gets a similar issue when `make` is run.

**Comment by umlaeute** [comment] 2020-10-28 11:53
thanks for the report.

however, please check the issue-archive before reporting.

closing this as a duplicate of #333 (and #364)

**Closed by umlaeute** 2020-10-28 11:53 UTC
