### ISSUE TITLE
DQBUF return bad index if queue bigger then 2 for capture

### ISSUE THREAD

**Issue by ndufresne** [umlaeute/v4l2loopback#60] opened 2014-05-25 03:45 UTC
I've been running some test, with queue of 4, but only keeping 1 or 2 queued buffer at the same time, I endup with wrong buffer id on dqbuf. This used to work in GStreamer because we where queued them all, before dqueueing 1. Hence, any random ID was valid.

**Comment by asmorkalov** [comment] 2015-08-19 11:54
Hello guys, do you determine failure reason?
I reproduce the same problem with Ubuntu 12.04 and Linux kernel 3.13. GStreamer reports "Failed to get 0 in input enumeration for /dev/video0. (25 - Inappropriate ioctl for device)" for all pipelines that try to write to this device. I tried several versions of v4l2loopback and detected that it's a regression that appears between 0.80 and 0.90. 0.80 works ok for me.

**Comment by spartan263** [comment] 2016-04-02 20:53
Debian Squeeze (EOL) / Linux 2.6.32-5-amd64

In chronological order, inclusive:
(ancient) – 9eb2b3c: ./test_dqbuf fails on 'S_FMT failed: Operation not permitted'
5987d40 – 4c664b3: kernel oops on  ./test_dqbuf launch
0d36924 – 92f155e: affected by `BUG #1` + `BUG #2`
1f9b485 – b330dd1: ./test_dqbuf aborts on `Assertion 'breq.count == 4'` failed.
8cb7ee5 – 1581d54: affected by `#1` + `#2`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^=> v0.5.0 is released in this range
390c10e – a252508: `#1` only
('git cherry-pick f69a2fa' is necessary starting at f06117c; appears to be unrelated)
b64337f – (current) : `#1` + `#2`, again
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...v0.6.0 released

==
Debian Jessie, Sid: `BUG #1` and `#2` as far back as can be seen before ./test_dqbuf sysfails on 'S_FMT' (somewhere around v0.6.2, with a fair amount of cherry-picking to complete builds)

**Comment by umlaeute** [comment] 2016-04-03 17:48
@spartan263  what's bug#1 and bug#2? i figure you are not referring to #1 and #2.

**Comment by spartan263** [comment] 2016-04-03 18:12
@umlaeute
"BUG #1" refers to "BUG #1: Driver should set the QUEUED flag before returning from QBUF"
"BUG #2" refers to "BUG #2: Driver should not dequeue a buffer that was not initially queued"
Both are generated by 'tests/test_dqbuf.c' are are indeed unrelated to GitHub issues.

**Comment by spartan263** [comment] 2016-04-07 16:13
Leaving working notes here for future reference.

Add timing debug statements to tests/test_dqbuf.c:
```
#include <time.h>
#include <sys/time.h>

  struct timeval now;
  struct tm *tmp;
  char timestr[9];
  int rc;
 
  for (i = 0; i < COUNT; i++) {
    rc = gettimeofday(&now, 0);
    tmp = localtime(&now.tv_sec);
    rc = strftime(timestr, sizeof(timestr), "%H:%M:%S", tmp);
    printf("post-QBUF     bufs[%d].flags = 0x%08X (%s.%06ld / test_dqbuf)\n", i,
           bufs[i].flags, timestr, now.tv_usec);
    }
```

...and likewise for v4l2loopback.c (note userspace<->kernel [time.h disparity](https://lkml.org/lkml/2012/10/19/230)):
```
   struct timespec tp;
 
   getnstimeofday(&tp);
   printk("vidioc_qbuf pre set_done buf->buffer.flags = 0x%08X (%ld.%ld / v4l2l)\n",
           b->buffer.flags, tp.tv_sec, tp.tv_nsec);
```

To the best of my limited ability I haven't found any glaring issues with v4l2loopback code; there seems to be a disconnect between the buffers the application creates and the buffers v4l2loopback sets flags on.

According to [v4l2 documentation](https://linuxtv.org/downloads/v4l-dvb-apis/buffer.html#buffer-flags) "After (successful) calling the VIDIOC_QBUF ioctl V4L2_BUF_FLAG_QUEUED is always set and after VIDIOC_DQBUF always cleared."  I'm not convinced that's true but would need to start kernel debugging to check.

**Closed** 2016-04-23 17:34 UTC
Labels: bug

**Comment by sanbrother** [comment] 2023-03-15 09:06
Specifying max_buffers solves the problem
`sudo modprobe v4l2loopback max_buffers=4`
