### ISSUE TITLE
Nv12 format not working

### ISSUE THREAD

**Issue by benlemond** [umlaeute/v4l2loopback#201] opened 2018-12-23 02:54 UTC
I have a piece of cpp code that writes frames to a loopback device and the pixelformat is set to *_NV12.  I am using chromium and it doesn't seem to 3bumerste the device.  However, if I only switch the pixelformat to *_RGB24 then chromium enumerates the output device correctly.

Is there a dependency somewhere within v4l on the format for chromium to enumerate those devices?  Is there a step being missed?

**Comment by simonchen007** [comment] 2019-02-13 10:24
does this issue resolved ?

**Comment by benlemond** [comment] 2019-02-13 13:57
No.  NV12 still was not working appropriately.  We switched to I420.

**Comment by umlaeute** [comment] 2019-02-13 19:37
closing this as a duplicate of #204.

**Closed by umlaeute** 2019-02-13 19:37 UTC
