### ISSUE TITLE
Make v4l2loopback is not working with kernel version 4.4.11-v7+

### ISSUE THREAD

**Issue by weiss19ja** [umlaeute/v4l2loopback#114] opened 2016-05-24 11:16 UTC
I tried to build the v4l2loopback module with the current jessie version of raspbian.   
Because there is no modules/4.4.11-v7+/build folder I also tried to get it to work with using the linux source files of the raspian.   
Has anybody an idea what I'm doing wrong?

**Comment by umlaeute** [comment] 2016-05-24 13:36
this is a duplicate of #84, #94, #104, #108 and probably others.

please file raspbian issues with their issue tracker, not here.

**Closed by umlaeute** 2016-05-24 13:36 UTC
