### ISSUE TITLE
Unable to compile the module

### ISSUE THREAD

**Issue by Riku32** [umlaeute/v4l2loopback#431] opened 2021-05-24 01:39 UTC
I am unable to compile the module on both master and develop, this is the compiler error I get

```
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/delta/Downloads/f/v4l2loopback modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-7614-generic'
  CC [M]  /home/delta/Downloads/f/v4l2loopback/v4l2loopback.o
during IPA pass: visibility
/home/delta/Downloads/f/v4l2loopback/v4l2loopback.c:2669:1: internal compiler error: Segmentation fault
 2669 | module_exit(v4l2loopback_cleanup_module);
      | ^~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
make[2]: *** [scripts/Makefile.build:287: /home/delta/Downloads/f/v4l2loopback/v4l2loopback.o] Error 1
make[1]: *** [Makefile:1848: /home/delta/Downloads/f/v4l2loopback] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-7614-generic'
make: *** [Makefile:46: v4l2loopback.ko] Error 2
```

I am currently on kernel 5.11.0-7614-generic

**Comment by umlaeute** [comment] 2021-05-25 09:06
this seems to be a problem with your build-setup (specifically: your compiler), rather than an issue with `v4l2loopback` itself.

as indicated by the error message, you should read `/usr/share/doc/gcc-10/README.Bugs` on how to create a bug-report for your compiler.

for now, i'm closing this as "not-for-us" (but feel free to bump if you have some evidence that the problem is indeed with *v4l2loopback*, so we can re-open it).

**Closed by umlaeute** 2021-05-25 09:06 UTC
Labels: needs triage
