### ISSUE TITLE
Error when building on Azure VM Ubuntu 18.04

### ISSUE THREAD

**Issue by tushar-wq** [umlaeute/v4l2loopback#444] opened 2021-09-24 09:28 UTC
azureuser@and-linux:~/v4l2loopback$ make

Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/azureuser/v4l2loopback modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-1056-azure'
  CC [M]  /home/azureuser/v4l2loopback/v4l2loopback.o
  Building modules, stage 2.
  MODPOST 1 modules
ERROR: "video_ioctl2" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_event_unsubscribe" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "__video_register_device" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_ctrl_handler_setup" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_ctrl_new_custom" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_ctrl_handler_init_class" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "video_device_release" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "video_device_alloc" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_device_register" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_fh_add" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_fh_init" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_event_pending" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_fh_exit" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_fh_del" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "video_devdata" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_ctrl_subscribe_event" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_ctrl_handler_free" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "v4l2_device_unregister" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
ERROR: "video_unregister_device" [/home/azureuser/v4l2loopback/v4l2loopback.ko] undefined!
scripts/Makefile.modpost:93: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
Makefile:1675: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-1056-azure'
Makefile:45: recipe for target 'v4l2loopback.ko' failed
make: *** [v4l2loopback.ko] Error 2

**Comment by umlaeute** [comment] 2021-09-24 09:42
the kernel lacks `v4l2` support.

also, this is a duplicate of https://github.com/umlaeute/v4l2loopback/issues/59

**Closed by umlaeute** 2021-09-24 09:42 UTC
Labels: needs triage
