### ISSUE TITLE
Linux 6.8.4 seems to have broken v4l2loopback in several ways. 

### ISSUE THREAD

**Issue by coppice-git** [umlaeute/v4l2loopback#584] opened 2024-04-06 21:27 UTC

**Comment by coppice-git** [comment] 2024-04-06 21:34
Fedora 39 has updated to Linux kernel 6.8.4 and this has broken v4l2loopback in several ways:
VFL_TYPE_GRABBER has gone. It seems VFL_TYPE_VIDEO should now be used instead, and is a direct replacement.
strlcpy() has gone. It looks like strscpy should be used instead, and is a direct replacement.
do_gettimeofday has gone. I think ktime_get() is supposed to be used now.
setup_timer() has gone. I'm not sure what the replacement for this looks like.

**Comment by umlaeute** [comment] 2024-04-07 09:18
Could you please replace the template description in the top posting with the actual description of the problem?

It says: 
> Please remove these instructions (and other non-relevant information) from your report.
If your report looks like a copy of the template, it might get closed immediately.

**Comment by angelosa** [comment] 2024-04-08 18:26
F39 version of v4l2loopback is v0.12.7, which seems incompatible (and rather old) with Linux kernel 6.8.4, it will throw deps errors when attempting to `modprobe`. A workaround is to git clone and compile `v4l2loopback`, cfr. this [tutorial section](https://github.com/seii/fedora-green-screen/blob/master/README.md#installing-v4l2loopback)

**Comment by umlaeute** [comment] 2024-04-08 19:11
Ah, so the issue is, that fedora ships a new kernel but an old `v4l2loopback` (that is known to not work with newer kernels anyhow, eg #570, #574, #575)?

Then I suppose, I can close this issue as "out of date".

(The template asks the module version for a reason... In any case I've updated the bug reporting template, so it becomes easier for people to provide the relevant information)

**Closed** 2024-04-08 19:11 UTC
Labels: needs triage

**Comment by coppice-git** [comment] 2024-04-08 19:15
I must have made a typo somewhere and didn't actually update my local repo copy. I just did a fresh checkout, and things work OK now. Thanks.

**Comment by umlaeute** [comment] 2024-04-09 05:39
great to know it works
