### ISSUE TITLE
v4l2loopback doesn't activate at startup

### ISSUE THREAD

**Issue by jconnolly837** [umlaeute/v4l2loopback#392] opened 2021-01-04 04:24 UTC
I'm using Fedora 33 Workstation, I successfully compiled and installed v4l2loopback. I'm able to activate the module by running "sudo modprobe v4l2loopback video_nr=2" and it's active for /dev/video2. But adding "options v4l2loopback video_nr=2" to /etc/modules-load.d/v4l2loopback.conf and running "sudo dracut -f" before restarting acts like I didn't even do anything. I did have "options v4l2loopback card_label="device number 2"" under "options v4l2loopback video_nr=2" in there for a while, I thought removing it might do something, but it did nothing. I also tried just having "v4l2loopback video_nr=2" and still nothing. 

Hopefully I'm just misunderstanding the readme instructions so someone can correct me. I'm sure I did this right, but it's obviously not working. 

I suppose it's not such a big deal, but I'd really prefer not having to activate the module manually between reboots if I wanna use v4l2loopback.

**Comment by umlaeute** [comment] 2021-01-04 20:31
dupe of #391

**Closed by umlaeute** 2021-01-04 20:31 UTC
Labels: duplicate
