### ISSUE TITLE
v4l2loopback module install fail

### ISSUE THREAD

**Issue by codedigger123** [umlaeute/v4l2loopback#149] opened 2017-11-11 09:55 UTC
## **Step 2: Describe your environment**
v4l2loopback version:
$sudo dmesg  | grep -i v4l2loopback

kernel version:
Linux Opti-test 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

##  **Step 3: Describe the problem:**
$ sudo make install
make -C /lib/modules/`uname -r`/build M=/home/test/v4l2loopback modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-38-generic'
  INSTALL /home/test/v4l2loopback/v4l2loopback.ko
At main.c:158:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.10.0-38-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-38-generic'

Anything else should be installed to solve it?thanks.

**Comment by umlaeute** [comment] 2017-11-11 11:56
afaict `make install` succeeds.
duplicate of #122, #139 and #144

**Closed by umlaeute** 2017-11-11 11:56 UTC
Labels: invalid
