### ISSUE TITLE
Build error for Ubuntu 19.04 when running: module-assistant auto-install v4l2loopback-source

### ISSUE THREAD

**Issue by RoelVdP** [umlaeute/v4l2loopback#233] opened 2019-09-24 03:52 UTC
```
# aptitude install v4l2loopback-source module-assistant
# module-assistant auto-install v4l2loopback-source
```

As described in the README, fails on Ubuntu 19.04 (Disco) in the second step with a build error;

```
 │ make[3]: Entering directory                                                 
 │ '/usr/src/linux-headers-5.0.0-23201908151420-generic'                       
 │   CC [M]  /usr/src/modules/v4l2loopback/v4l2loopback.o                      
 │ /usr/src/modules/v4l2loopback/v4l2loopback.c: In function ‘vidioc_qbuf’:    
 │ /usr/src/modules/v4l2loopback/v4l2loopback.c:1509:4: error: implicit        
 │ declaration of function ‘v4l2_get_timestamp’; did you mean                  
 │ ‘v4l2_get_subdevdata’? [-Werror=implicit-function-declaration]              
 │     v4l2_get_timestamp(&b->buffer.timestamp);                               
 │     ^~~~~~~~~~~~~~~~~~                                                      
 │      v4l2_get_subdevdata                                                     
 │ cc1: some warnings being treated as errors                                  
 │ make[4]: *** [scripts/Makefile.build:293:                                   
 │ /usr/src/modules/v4l2loopback/v4l2loopback.o] Error 1                       
 │ make[3]: *** [Makefile:1606: _module_/usr/src/modules/v4l2loopback] Error   
 │ 2                                                                           
 │ make[3]: Leaving directory                                                  
 │ '/usr/src/linux-headers-5.0.0-23201908151420-generic'                       
 │ make[2]: *** [Makefile:43: v4l2loopback.ko] Error 2                         
 │ make[2]: Leaving directory '/usr/src/modules/v4l2loopback'                  
 │ make[1]: *** [debian/rules:17: binary-modules] Error 2                      
 │ make[1]: Leaving directory '/usr/src/modules/v4l2loopback'                  
 │ make: *** [/usr/share/modass/include/common-rules.make:56: kdist_build]     
 │ Error 2        
```

Please fix. Should be easy to repeat, just setup a Ubuntu 19.04 Disco x64 and enter those two commands. Seems like perhaps a simple compiler flag change may fix it.

**Comment by umlaeute** [comment] 2019-09-24 08:03
- have you tried the latest release of `v4l2loopback`? (at time of writing this is 0.12.2)
- If you only use packages from your distro, please report the bug with your distro
- have you looked at other issues in this tracker (and did you see #214)?

the underlying problem is, that `v4l2loopback<<0.12.1` lacked support for linux-5.0.
Linux-5 support has been added in afe0b233070d7ca5d6df83c5f2723d276dcd287d (Linux-0.5 support; found in `v4l2loopback-0.12.1') and 376c2c28bd7d4470cd92ff646d6087ca70cd9d2e (Linux-5.1 support, found in `v4l2loopback-0.12.2').

I'm not entirely sure why the linux-5.0.0 headers as shipped with Ubuntu require the Linux-5.1 fix (but there's the ominous `23201908151420` in the version string...), but in any case: the problem is fixed (and a duplicate of #214)

**Closed by umlaeute** 2019-09-24 08:03 UTC
