### ISSUE TITLE
Creating QSocketNotifier is getting failed 

### ISSUE THREAD

**Issue by Ramsonjehu** [umlaeute/v4l2loopback#256] opened 2020-02-18 15:51 UTC
Environment:

  * `v4l2loopback` version: 0.12.3
  * kernel version: 4.15.0-76-generic
  * Distribution (+version): ubuntu 16.04
  
Problem:
I have created a video node using:

~~~sh
 sudo insmod v4l2loopback.ko devices=1
~~~

and I'm feeding GStreamer videotestsrc as input to the video node using;
~~~sh
gst-launch-1.0 -v videotestsrc pattern=ball  ! v4l2sink device=/dev/video0
~~~

Done with that, I'm trying to use Qtcam(https://github.com/econsysqtcam/qtcam) application to stream the video node. In that application, they have created a QSocketNotifier using:

~~~C++
        // This line causes error
        m_capNotifier = new QSocketNotifier(fd, QSocketNotifier::Read);
        // where fd is the file descriptor of video node /dev/video0
        connect(m_capNotifier, SIGNAL(activated(int)), this, SLOT(capFrame()));
~~~

to notify whenever the buffer is ready to read. 
This causes an error, I'm unable to create that socket notifier, it showed me error as "QSocketNotifier: Invalid socket specified". When I went into the source code of QSocketNotifier, I found that this error caused because that fd is invalid. But I checked the fd before the line that caused the error, it was valid. See line number 151 in the following link.
https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qsocketnotifier.cpp.html#145

Steps to reproduce:
  1.  have created a video node using:
       sudo insmod v4l2loopback.ko devices=1
  2. feed GStreamer videotestsrc as input to the video node using;
      gst-launch-1.0 -v videotestsrc pattern=ball  ! v4l2sink device=/dev/video0
  3. Open fd.
  4. register QSocketNotifier using 
      m_capNotifier = new QSocketNotifier(fd, QSocketNotifier::Read);
 
  
Observed Results:
error produced:
  "QSocketNotifier: Invalid socket specified"
  
Expected Results:

  * QSocketNotifier should get registered and notify whenever the buffer is ready to read.

**Comment by umlaeute** [comment] 2020-02-25 08:44
this seems to be a Qt Programming problem, rather than an issue with `v4l2loopback`, so I'm closing this for now.

if you are convinced that this is indeed a problem with `v4l2loopback`, please post a [complete, minimal example that exposes the problem](https://stackoverflow.com/help/minimal-reproducible-example). (your "steps to reproduce" are a good start, but 3. and 4. ought to be replaced by a compilable program)

**Closed by umlaeute** 2020-02-25 08:44 UTC
